---
BUILD_DIR: "/root"
ADMIN_A: "admin"
SAVE_FREQ: "2"
USE_DEPRECATED_ENDPOINTS: "true"
WEB_ENABLED: true
WEB_PORT: "3000"
CCASH_PORT: 8080
CCASH_PORT_S: 8443
START_SERVICES: false
START_ON_BOOT: true
BRANCH: "main"